stages:
  - deploy

deploy:
  stage: deploy

  image:
    name: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest

  id_tokens:
    MY_OIDC_TOKEN:
      aud: https://gitlab.com

  before_script:
    - set -x
    - mkdir -p ~/.aws
    - echo "${MY_OIDC_TOKEN}" > /tmp/web_identity_token
    - echo -e "[profile oidc]\nrole_arn=${ROLE_ARN}\nweb_identity_token_file=/tmp/web_identity_token" > ~/.aws/config
    - cat ~/.aws/config

  script:
    # 0. Create the zip
    - zip -r application.zip . -x ".git/*"

    # 1. Upload the artifact to S3
    - aws deploy push
      --profile oidc
      --application-name "$CODEDEPLOY_APPLICATION"
      --s3-location s3://"$DEPLOY_BUCKET/releases/$CI_COMMIT_SHA.zip"

    # 2. Trigger the CodeDeploy deployment
    - aws deploy create-deployment 
      --profile oidc
      --application-name "$CODEDEPLOY_APPLICATION"
      --deployment-group-name "$CODEDEPLOY_DEPLOYMENT_GROUP"
      --deployment-config-name CodeDeployDefault.OneAtATime
      --s3-location bucket="$DEPLOY_BUCKET",key="releases/$CI_COMMIT_SHA.zip",bundleType=zip 
      --description "GitLab deployment $CI_COMMIT_SHA"

  only:
    - main
